#
# To build:
# 1.) Update the .env file with the correct URL 
# 2.) Run `docker-compose build --no-cache`
#
# To run:
# 1.) Make sure programs running in the container can connect to your X server by running `xhost +`
# 2.) Run `docker-compose up` to test the webcam demo, or modify the command below to test the video demo.

version: '3'
services:
  ics_2_0:
    build: 
      context: cpp-sdk-samples/.
      args: 
        - AFFECTIVA_AUTO_SDK_2_0_URL=${AFFECTIVA_AUTO_SDK_2_0_URL} 
        - BRANCH=${BRANCH} 
    image: affectiva-auto:v2.0-ics
    network_mode: host # need this for X11
    #privileged: true # need this to access some devices
    devices:
      - /dev/video0:/dev/video0 # change /dev/video0 with your video device
      - /dev/snd # for speech demo
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/root/.Xauthority
            
    environment:
      - "DISPLAY=${DISPLAY}"

    
    command: "/opt/testapp-artifact/build/vision/bin/frame-detector-webcam-demo -d /opt/testapp-artifact/affectiva-ics-sdk-2.0.0/data" # you can comment this out to get a bash prompt
    #command: '/opt/testapp-artifact/build/vision/bin/frame-detector-video-demo -d /opt/testapp-artifact/affectiva-ics-sdk-2.0.0/data -i "sample.mp4" --numFaces 50'

